# Project configuration
project_id = "wibxjlottpxnpjbaoajh"  # Your Supabase project ID
api_url = "https://wibxjlottpxnpjbaoajh.supabase.co"    # Your Supabase project URL

[auth]
# Enable email/password authentication
enable_email_signup = true
enable_email_signin = true

# Email template settings
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]

# Password settings
min_password_length = 8

[database]
# Database settings
postgres_version = "15"

[api]
# API settings
port = 54321
schemas = ["public", "auth", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[studio]
# Studio settings
port = 54323

[storage]
# Storage settings
file_size_limit = "50MiB" 