name = "zurisbeautystore"
compatibility_date = "2024-02-20"
compatibility_flags = ["nodejs_compat"]

# Production environment
[env.production]
NODE_VERSION = "20"
NODE_ENV = "production"
compatibility_flags = ["nodejs_compat"]

# Preview environment
[env.preview]
NODE_VERSION = "20"
NODE_ENV = "development"
compatibility_flags = ["nodejs_compat"]

# Build configuration
[build]
command = "npm run pages:build"
pages_build_output_dir = ".vercel/output/static"

# Pages configuration
[pages]
build_output_directory = ".next"
include = [
  "public/*",
  ".next/static/*",
  ".next/server/*",
  ".next/standalone/*"
]
exclude = [
  "node_modules/**/*",
  ".git/**/*",
  ".next/cache/**/*",
  "**/*.pack",
  "**/*.pack.*",
  ".next/trace",
  ".next/types"
]

[site]
bucket = ".vercel/output/static"

[build.upload]
format = "service-worker" 
