name = "zurisbeautystore"
compatibility_date = "2024-02-20"
compatibility_flags = ["nodejs_compat"]

[env.production]
NODE_VERSION = "20.11.1"


[build]
command = "npm run build"
output_directory = ".next"

[deployment]
routes = [
  { pattern = "/*", zone_name = "zurisbeautystore" }
]

# Add Pages configuration
pages_build_output_dir = ".next"

[site]
bucket = ".next" 
