name = "zurisbeautystore"
compatibility_date = "2024-02-15"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
output_directory = ".next"

[env.production]
NODE_VERSION = "20.11.0"

[site]
bucket = ".next" 