name = "zurisbeautystore"
compatibility_date = "2024-02-20"
compatibility_flags = ["nodejs_compat"]

[env.production]
NODE_VERSION = "18.17.1"
NODE_ENV = "production"
SUPABASE_URL = ""
SUPABASE_ANON_KEY = ""

# Build configuration
[build]
command = "npm run pages:build"
pages_build_output_dir = ".vercel/output/static"

# Pages configuration
[pages]
build_output_directory = ".next"
include = [
  "public/*",
  ".next/static/*",
  ".next/server/*",
  ".next/standalone/*"
]
exclude = [
  "node_modules/**/*",
  ".git/**/*",
  ".next/cache/**/*",
  "**/*.pack",
  "**/*.pack.*",
  ".next/trace",
  ".next/types"
]

[site]
bucket = ".vercel/output/static"

[build.upload]
format = "service-worker"

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://pxsrrupipvqyccpriceg.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4c3JydXBpcHZxeWNjcHJpY2VnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAxMzgxNjgsImV4cCI6MjA1NTcxNDE2OH0.N5L8MmF17oeUs2MVFw6oDbFA3nbw0NODdVLyoa8FxCE" 
