name = "zurisbeautystore"
compatibility_date = "2024-02-20"
compatibility_flags = ["nodejs_compat"]

[env.production]
NODE_VERSION = "20.11.1"

[build]
command = "npm run pages:build"

[deployment]
routes = [
  { pattern = "/*", zone_name = "zurisbeautystore" }
] 